name: Publish Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetching tags
        run: git fetch --tags -f || true
      
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish in NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
